apiVersion: apps/v1
kind: Deployment
metadata:
  name: mc-vanilla-1
  namespace: minecraft
spec:
  replicas: 1
  selector:
    matchLabels:
      app: mc-vanilla-1
  template:
    metadata:
      labels:
        app: mc-vanilla-1
    spec:
      containers:
        - image: docker.io/itzg/minecraft-server
          name: mc-vanilla-1
          resources:
            requests:
              memory: "256Mi"
              cpu: "200m"
            limits:
              memory: "2048Mi"
              cpu: "1000m"
          env:
            # Use secret in real usage
          - name: EULA
            value: "true"
            # Use secret in real usage
          - name: ENABLE_AUTOPAUSE
            value: "true"
          ports:
          - containerPort: 25565
            name: main
          startupProbe:
            exec:
              command: ["/health.sh"]
            initialDelaySeconds: 20
            periodSeconds: 20
            failureThreshold: 30
          readinessProbe:
            exec:
              command: ["/health.sh"]
            initialDelaySeconds: 20
            periodSeconds: 20
            failureThreshold: 20
          # Monitor ongoing liveness
          # livenessProbe:
          #   exec:
          #     command: ["/health.sh"]
          #   initialDelaySeconds: 120
          #   periodSeconds: 60
          
          volumeMounts:
            - name: mc-data-1
              mountPath: /data
      volumes:
        - name: mc-data-1
          emptyDir: {}